services:
  ml_api:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ml_template_service
    ports:
      - "8000:8000"
    volumes:
      - ../mlruns:/app/mlruns:ro
      - ../mlflow.db:/app/mlflow.db:ro
    environment:
      - APP_MODE=dev
      - MLFLOW_TRACKING_URI=${MLFLOW_EXPERIMENT_NAME}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3